name: PySJTU Builds

on:
  push:
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: pdm-project/setup-pdm@v4
      name: Setup PDM and Python 3.12
      with:
        python-version: "3.12"
        cache: true
        version: 2.15.4

    - name: Install dependencies
      run: pdm sync -G tests -G ocr

    - name: Test if no syntax error
      run: |
        pdm run flake8 . --exclude .venv --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: pdm run pytest

    - name: Upload package to PyPI
      run: pdm publish
      env:
        PDM_PUBLISH_USERNAME: "__token__"
        PDM_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN }}